image: erpukraine/pipelines:default-image-2
clone:
  depth: 1

pipelines:
  default:
    - step:
        name: Unit Tests
        script:
          - export REPO="erpukraine/custom" PROJECT="${BITBUCKET_REPO_SLUG}" VERSION="15.0"
          - if [[ -v BITBUCKET_BUILD_NUMBER ]]; then VERSION=${BITBUCKET_BUILD_NUMBER}; fi
          - export IMAGE_NAME=${REPO}:${PROJECT}-${VERSION}
          - >
            export UPDATED_MODULES=`ls ./extra-addons/ | awk -vORS=, '{ print $1 }' | sed 's/,$/\n/'`
          - if [[ ${UPDATED_MODULES} == "" ]]; then echo "Nothing to test"; exit 0; fi
          - echo "Testing ${UPDATED_MODULES}"
          - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          - sed -i -e "s/without_demo =.*/without_demo = False/g" odoo.conf
          - sed -i -e "s/db_host =.*/db_host = host.docker.internal/g" odoo.conf
          - docker build --build-arg SAAS_IMG=erpukraine/custom:odoo-15.0ee-erpu-latest -t ${IMAGE_NAME} .
          - mkdir ${BITBUCKET_CLONE_DIR}/data && chmod 777 ${BITBUCKET_CLONE_DIR}/data
          - >
            docker run --rm -t --name=${PROJECT}-${VERSION} --add-host host.docker.internal:${BITBUCKET_DOCKER_HOST_INTERNAL}
            -v ${BITBUCKET_CLONE_DIR}/data:/var/lib/odoo -e "HOST=host.docker.internal" ${IMAGE_NAME}
            -i ${UPDATED_MODULES} -d test-db --db_host host.docker.internal --db-filter=test-db --workers=0 --stop-after-init
          - >
            docker run --rm -t --name=${PROJECT}-${VERSION} --add-host host.docker.internal:${BITBUCKET_DOCKER_HOST_INTERNAL}
            -v ${BITBUCKET_CLONE_DIR}/data:/var/lib/odoo -e "HOST=host.docker.internal"
            -e "COVERAGE_FILE=/tmp/.coverage" -e "MARICHKA_KEY=${MARICHKA_KEY}" ${IMAGE_NAME}
            /bin/bash -c "set -e; coverage run /usr/bin/odoo
            -u ${UPDATED_MODULES} --workers=0 -d test-db --stop-after-init --test-enable -w odoo -r odoo
            --db_host host.docker.internal --db-filter=test-db; coverage report
            --omit *system_site_packages*,*site-packages*,*dist-packages*,*pyshared*,*enterprise-addons* "
        services:
          - postgres
          - docker
  branches:
    master:
      - step:
          name: Build and Push
          services:
            - docker
          script:
            - (echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin)
            - docker build -t erpukraine/custom:penguin-15.0-${BITBUCKET_BUILD_NUMBER} .
            - docker push erpukraine/custom:penguin-15.0-${BITBUCKET_BUILD_NUMBER}
      - step:
          name: Deploy
          deployment: production
          trigger: manual
          services:
            - docker
          script:
             - echo "Configure deployment for v15"
#            - ansible-playbook deploy-prod.yml -i "penguin.swiss," -e BITBUCKET_BUILD_NUMBER=$BITBUCKET_BUILD_NUMBER

definitions:
  services:
    postgres:
      image: postgres:12
      environment:
        POSTGRES_PASSWORD: odoo
        POSTGRES_USER: odoo
