version: '3.2'

volumes:

  pg10penguin15:
    driver: local

  odoo15penguin-container-data:
    driver: local

  odoo15penguin-data:
    driver: local

  vscode-data:
    driver: local

services:

  db-penguin15:
    image: postgres:10.5
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - pg10penguin15:/var/lib/postgresql/data

  web-penguin15:
    links:
      - db-penguin15
    tty: true
    image: erpukraine/custom:odoo-15.0ee-erpu-latest
    depends_on:
      - db-penguin15
    environment:
      - HOST=db-penguin15
    ports:
      - "3000:3000"
      - "8069:8069"
    volumes:
      - ./:/mnt/extra-addons:cached
      - odoo15penguin-container-data:/home/vscode/.local/share/Odoo
      - odoo15penguin-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - vscode-data:/home/vscode/.vscode-server
