{
    'name': 'Payment Wire Transfer Confirmation',
    'summary': 'Auto confirm orders, create invoices and post them for wire transfer payments',
    'author': 'ERP Ukraine',
    'website': 'https://erp.co.ua',
    'support': 'support@erp.co.ua',
    'license': 'LGPL-3',
    'category': 'Accounting/Payment',
    'version': '1.2',
    'depends': ['payment_transfer', 'sale'],
    'data': [
        'data/payment_data.xml',
        'views/payment_acquirer_views.xml',
        'views/payment_transaction_views.xml',
    ],
    'auto_install': False,
    'installable': True,
    'application': False,
    'post_init_hook': 'wire_transfer_enable_authorization',
}
