{
    'name': 'Website Sale Stock Multi Warehouse',
    'summary': 'Allow to use multiple warehouses for each website',
    'author': 'ERP Ukraine LLC',
    'website': 'https://erp.co.ua',
    'support': 'support@erp.co.ua',
    'license': 'LGPL-3',
    'category': 'Website/Website',
    'version': '1.0',
    'depends': ['website_sale_stock'],
    'data': ['views/res_config_settings_views.xml'],
    'installable': True,
    'auto_install': False,
    'application': False,
}
