# -*- coding: utf-8 -*-
{
    'name': 'Penguin Website',
    'author': 'ERP Ukraine',
    'website': 'https://erp.co.ua',
    'support': 'support@erp.co.ua',
    'license': 'LGPL-3',
    'category': 'Website/Website',
    'version': '3.0',
    'sequence': 7,
    'depends': ['website'],
    'data': [
        'views/aboutus.xml',
        'views/accessoires.xml',
        'views/ambassador.xml',
        'views/care.xml',
        'views/customerservice.xml',
        'views/fleece.xml',
        'views/homepage.xml',
        'views/insulation.xml',
        'views/merino.xml',
        'views/movie.xml',
        'views/shell.xml',
        'views/philosophy.xml',
        'views/stores.xml',
        'views/toursandevents.xml',
        'data/website_data.xml',
    ],
    'installable': True,
    'auto_install': True,
    'application': False,
}
